/**
 * GENERATED by scripts/image-audit.mts — do not edit by hand.
 *
 * Frames that decode to a single flat colour: files that exist, decode without error, and are
 * pictures of nothing. They are indistinguishable from real photographs to every part of the
 * stack except a pixel measurement, which is what produced this list.
 *
 * `lib/hero-image.ts` treats a frame named here exactly as it treats one the pipeline flagged as
 * a placeholder — kept in the gallery, never allowed to lead.
 *
 * Regenerate with: pnpm --filter @buildobjects/web images:audit --write
 */

/** SKU code (upper case) -> the 1-based frame positions that carry no image. */
export const BLANK_FRAMES: Readonly<Record<string, readonly number[]>> = {
  'TIL-JOH-YK1FLCR000000PJ': [3, 4],
  'TIL-SOM-T31F119001859102': [1, 2, 3, 4],
};

/** Is this product's frame at `position` a blank? */
export const isBlankFrame = (skuCode: string, position: number): boolean => BLANK_FRAMES[skuCode.toUpperCase()]?.includes(position) === true;
