/**
 * Which of a product's photographs leads.
 *
 * The pipeline fills a gallery to five frames and writes a drawn placeholder — a dark card
 * carrying the product's name and the words "Official image pending" — wherever it could not find
 * a real photograph. Nine of the twenty-seven stocked products have at least one, which is fine:
 * they sit at the end of the gallery where a reader who has scrolled that far can see for
 * themselves that the set is short.
 *
 * On one, `CCT-DAH-HDW1200TRQP`, the placeholder is at position 1. Position 1 is the hero, so that
 * card was the product's face on the CCTV category page, in every search result, and at the top of
 * its own product page — a tile that says "Official image pending" in a shop, next to four real
 * photographs of the camera that were already on disk and simply ordered behind it.
 *
 * So: a placeholder is never the hero while a real frame exists. That is the rule, and it is
 * defensive rather than cosmetic — the pipeline can order images however it likes and the
 * storefront still leads with a photograph.
 */
import { BLANK_FRAMES, isBlankFrame } from './blank-frames';
import type { SkuImageView } from './catalog';

/**
 * A frame that must not lead: one the pipeline flagged as a placeholder, or one that is a picture
 * of nothing.
 *
 * The second kind is why this function exists rather than a `.placeholder` check inline. Somany's
 * Duragres tile shipped four frames that decode to a single flat colour — real files, valid WebP,
 * 282 bytes each — and the fifth was the only photograph. Nothing in the pipeline flagged them,
 * because as far as any of it could tell they were images. So the store led with an empty box on
 * the category page, in search, and on the product's own page.
 *
 * `lib/blank-frames.ts` is generated by measuring the pixels (scripts/image-audit.mts). Treating
 * a measured blank exactly like a declared placeholder is what makes the existing rule cover both.
 */
const unusable = (skuCode: string, image: SkuImageView): boolean => image.placeholder || isBlankFrame(skuCode, image.position);

/**
 * Role preference, once placeholders are out of the way.
 *
 * `hero` is what a brand shot for this purpose; `angle` is the same product from another side;
 * `detail` is a crop; `in_context` has a room in it, which makes a poor thumbnail; and
 * `pack_or_dimensions` is a line drawing. That order is the order a picture editor would pick in.
 */
const ROLE_RANK: Record<string, number> = { hero: 0, angle: 1, detail: 2, in_context: 3, pack_or_dimensions: 4 };

/**
 * Products whose role labels are wrong in the source data, and cannot be repaired by any rule.
 *
 * `CCT-DAH-HDW1200TRQP` is a HAC-HDW1200TRQ, which is a TURRET — an "eyeball" — camera. Its five
 * frames are labelled hero/angle/in_context/detail/pack, and of them only the one labelled
 * `detail` is a turret at all: the `angle` frame is a bullet camera, a different body style
 * entirely, and its alt text describes an eyeball while showing one. So the role order above would
 * replace a placeholder with a photograph of the wrong product, which is a worse failure than the
 * placeholder it fixes — it looks correct.
 *
 * This is a catalogue defect and belongs upstream in the image pipeline, not here. Until it is
 * fixed there, this one line stops the storefront misrepresenting the product. It is a list of
 * exceptions and it should stay short; if it grows, the pipeline is what needs the work.
 */
const ROLE_OVERRIDE: Record<string, number> = {
  'CCT-DAH-HDW1200TRQP': 4,
};

/**
 * The gallery, reordered so it leads with a real photograph.
 *
 * Everything is kept — a placeholder still appears, just never first — because a five-frame
 * gallery that silently becomes a four-frame one hides how thin the set is. Order is otherwise
 * untouched, so the sequence a reader arrows through is the one the pipeline intended.
 */
export function leadWithRealPhoto(skuCode: string, images: SkuImageView[]): SkuImageView[] {
  if (images.length < 2 || !images[0] || !unusable(skuCode, images[0])) return images;

  const forced = ROLE_OVERRIDE[skuCode.toUpperCase()];
  const usable = images.filter((i) => !unusable(skuCode, i));
  const lead =
    (forced !== undefined ? usable.find((i) => i.position === forced) : undefined) ??
    [...usable].sort((a, b) => (ROLE_RANK[a.role] ?? 9) - (ROLE_RANK[b.role] ?? 9) || a.position - b.position)[0];

  if (!lead) return images;
  return [lead, ...images.filter((i) => i !== lead)];
}

/**
 * The same correction, applied to a search document's `hero_image_key`.
 *
 * A card, a search hit and the home page's stock panel do not carry a gallery — they carry one
 * key, chosen when the product was indexed. Re-deriving it would mean reading the image rows for
 * every hit on every listing page, so this rewrites the position segment of the key instead:
 * `skus/81/CCT-DAH-HDW1200TRQP/img/1-card.webp` becomes `…/4-card.webp`, and every rendition
 * (thumb, card, gallery, zoom) of position 4 already exists beside it.
 *
 * Keyed off the same ROLE_OVERRIDE, so the gallery and the card cannot disagree about which
 * photograph is this product's face.
 */
export function correctHeroKey(skuCode: string, key: string | null): string | null {
  if (!key) return key;
  const override = ROLE_OVERRIDE[skuCode.toUpperCase()];
  if (override !== undefined) return key.replace(/\/img\/\d+-/, `/img/${override}-`);

  /*
   * A card carries one key, chosen when the product was indexed, and no gallery to reorder — so
   * the blank-frame correction has to be done on the key itself. The position segment is rewritten
   * to the first frame that is not blank; every rendition of that position already exists beside
   * it, so `…/1-card.webp` becoming `…/5-card.webp` needs nothing else to change.
   *
   * Keyed off the same generated list the gallery uses, so a card and the product page it opens
   * cannot disagree about which photograph is this product's face.
   */
  const at = key.match(/\/img\/(\d+)-/);
  if (!at || !isBlankFrame(skuCode, Number(at[1]))) return key;
  const blank = BLANK_FRAMES[skuCode.toUpperCase()] ?? [];
  /* Frames are 1-based and there are five; the first one not on the blank list is the face. */
  for (let position = 1; position <= 5; position++) if (!blank.includes(position)) return key.replace(/\/img\/\d+-/, `/img/${position}-`);
  return key;
}
