/* GENERATED by scripts/trace-mark.mts from public/logo-mark.png — run that again rather than editing this. */

/** The PNG's own pixel grid; every number below is in it. */
export const MARK_VIEW = 815;

/** The three stems, left to right, as closed paths. */
export const MARK_STEMS: readonly [string, string, string] = [
  'M277 49.1 L319.6 49.1 L65.7 765.8 L24.6 765.8 Z',
  'M359.2 49.1 L402 49.1 L145.3 765.8 L104.1 765.8 Z',
  'M441.8 49.1 L485 49.1 L225.2 765.8 L183.7 765.8 Z',
];

/** The bowl's outer ring, from the top cut clockwise to the bottom cut and back along its inner face. */
export const MARK_RING_OUTER =
  'M454.4 238.2 L628 238.5 L645.9 240.5 L662.9 244.5 L677.9 249.5 L691.6 255.5 L699.3 259.5 L713.8 268.5 L720.7 273.5 L731.6 282.5 L744.1 294.5 L751.9 303.5 L760.9 315.5 L770.8 331.5 L778.9 349.5 L784.7 366.5 L788.5 383.5 L790.5 398.5 L791.1 411.5 L791 419.5 L790.7 426.5 L789.1 439.5 L786.7 450.5 L781.8 466.5 L739.1 579.5 L721.7 627.5 L714.8 642.5 L706 658.5 L698.2 670.5 L689.2 682.5 L675.1 698.5 L666.9 706.5 L654.2 717.5 L643.7 725.5 L636.3 730.5 L624.8 737.5 L613.7 743.5 L595.7 751.5 L578.8 757.5 L566.9 760.5 L557 762.5 L544.1 764.5 L532 765.5 L263.9 765.8 L279.8 721.7 L530 721.5 L541.8 720.5 L554 718.5 L562.9 716.5 L578.8 711.5 L596.7 703.5 L607.7 697.5 L613.9 693.5 L621.2 688.5 L628.8 682.5 L635.7 676.5 L642.9 669.5 L657.8 652.5 L663.7 644.5 L673.6 628.5 L681.2 612.5 L702.1 555.5 L734.7 468.5 L740.9 451.5 L743.6 442.5 L745.7 431.5 L746.7 421.5 L746.9 415.5 L746.6 406.5 L745.9 399.5 L743.6 386.5 L740.6 374.5 L735.6 361.5 L732.3 354.5 L727.3 345.5 L722 337.5 L715.9 329.5 L704.7 317.5 L693.1 307.5 L681.6 299.5 L670.8 293.5 L661.9 289.5 L653.8 286.5 L642.9 283.5 L630.9 281.5 L439.1 280.6 Z';

/** The bowl's inner ring, the same way round. */
export const MARK_RING_INNER =
  'M423.3 324.5 L428 324.5 L602.9 325.5 L614.1 327.5 L621.8 329.5 L627.7 331.5 L634.7 334.5 L642.7 338.5 L655 346.5 L664.1 354.5 L670.6 361.5 L677.9 371.5 L684.4 383.5 L688.8 395.5 L691.5 406.5 L692.4 413.5 L693 423.5 L692.2 436.5 L689 450.5 L659.8 529.5 L640.1 584.5 L633.2 600.5 L629.2 607.5 L626.2 612.5 L619 622.5 L614.1 628.5 L608.5 634.5 L596.5 645.5 L589.9 650.5 L583.8 654.5 L577.2 658.5 L569.4 662.5 L562.8 665.5 L554.7 668.5 L539.9 672.5 L526 674.5 L296.7 675.1 L312.4 631.6 L515 631.5 L529.9 629.5 L537.8 627.5 L543.8 625.5 L551 622.5 L556.7 619.5 L564.8 614.5 L574.9 606.5 L582.6 598.5 L588.9 590.5 L593.7 582.5 L596.7 576.5 L646.6 440.5 L648 434.5 L648.7 427.5 L648.1 419.5 L647.1 413.5 L645.7 408.5 L643.4 402.5 L638 393.5 L630.9 385.5 L628.6 383.5 L621.7 378.5 L616.3 375.5 L606.9 371.5 L598.2 369.5 L590 368.5 L407.4 368.3 Z';

/** Each ring's centreline, starting just before the top cut and ending just past the bottom one. */
export const MARK_SPINE_OUTER =
  'M430.4 259.8 L627.9 260.1 L642.3 261.8 L656.8 265.3 L670 269.6 L681.9 274.8 L699.2 284.7 L707.9 290.9 L724.1 305 L739.4 322.6 L751.6 341.4 L759.1 358 L764.4 373.9 L767.3 387.5 L769.1 401.5 L769.5 414.9 L768.7 430.3 L765.8 445.2 L762.6 456.3 L701.8 618.9 L691.8 639.8 L680.5 658 L669.6 672.4 L652.3 690.6 L631 708 L614 718.8 L592.3 729.6 L572.8 736.7 L553.1 741.2 L531.9 743.9 L239.9 744.2';
export const MARK_SPINE_INNER =
  'M399.2 346.3 L602.7 347.3 L615.7 350.5 L630 356.5 L641.3 363.5 L651.4 372.7 L658.7 381.9 L662.6 388.6 L666.8 398.3 L669.7 408.6 L670.7 416 L670.6 433.2 L667.5 446.6 L617.9 581.2 L614 590.1 L604.1 606.1 L595.6 616.3 L583.3 628.1 L572.2 636 L559.8 642.9 L547.7 647.8 L535.6 651.1 L525.9 652.7 L272.6 653.3';

/** A stroke this wide along a spine covers its ring with a margin on both faces. */
export const MARK_SPINE_STROKE = 78;

/**
 * The middle stem's axis: its centre, its two ends (bottom first), its length, and the degrees a
 * horizontal line rotates — clockwise positive, so negative here — to lie along it.
 */
export const MARK_AXIS = {
  x: 252.7,
  y: 407.4,
  from: [124.7, 765.8] as const,
  to: [380.6, 49.1] as const,
  length: 761.1,
  angle: -70.35,
} as const;

/** Perpendicular distance from the first stem's outer face to the third's — the width of the stroke group. */
export const MARK_BAND = 192.4;

/** Perpendicular thickness of one stem. */
export const MARK_STEM = 39.6;
