/**
 * GENERATED by scripts/blend-skus.mts — do not edit by hand.
 *
 * The colour each SKU's first image sits on, sampled from its own border. It is painted behind
 * that product wherever the product appears, so the photograph's background and the mount behind
 * it are the same colour and there is no rectangle. Most are the shared silver the blend pass
 * put them on; the outliers are suppliers who shipped a marketing composite rather than a
 * photograph, and those keep the colour their artwork was drawn on.
 */
export const PLATE_COLORS: Record<string, string> = {
  'BUL-HAV-LEDPLUS9WB22': '#16333b',
  'BUL-PHI-ACESAVER9WB22': '#16333b',
  'BUL-WIP-GARNET9WB22': '#16333b',
  'CCT-CPP-USC-TA24L2C-L': '#082229',
  'CCT-DAH-HDW1200TRQP': '#09242c',
  'CCT-HIK-2CE76D0T-ITPFS': '#082229',
  'CEM-ACC-SP50': '#082229',
  'CEM-AMB-KAWACH50': '#16333b',
  'CEM-AMB-PLUS50': '#082229',
  'CEM-ULT-PPC50': '#16333b',
  'EPX-FOS-CONBEXTRAEP10': '#16333b',
  'EPX-PID-EPOXYINJGROUT': '#16333b',
  'EPX-SIK-SIKADUR31IN': '#16333b',
  'FIR-CEA-MAP90-4KG': '#16333b',
  'FIR-NEW-CA-EB-01': '#16333b',
  'FIR-SAF-ABC-SP-6KG': '#16333b',
  'GLS-GUA-CLIMAGUARD-BLUE5': '#c6d8e7',
  'GLS-SGB-SUNBAN-SAPPHIRE5': '#16333b',
  'SOL-ADA-ASB-M10-144-575': '#082229',
  'SOL-VIK-PARADEA-550': '#082229',
  'SOL-WAA-BI55-545': '#16333b',
  'TIL-JOH-YK1FLCR000000PJ': '#f3e7d1',
  'TIL-KAJ-GP00215': '#16333b',
  'TIL-SOM-T31F119001859102': '#16333b',
  'TST-LEI-TS07-2-R500': '#16333b',
  'TST-TOP-GM-52': '#16333b',
  'TST-TRI-C5-2': '#0063a4',
};

/** The mount for a SKU, or null to fall back to the shared --plate-1. */
export const plateFor = (sku: string): string | null => PLATE_COLORS[sku] ?? null;
