import { decode } from 'blurhash';

/**
 * THE MOUNT A FRAME IS PAINTED ON, TAKEN FROM THE FRAME ITSELF.
 *
 * The store mounts every product photograph on `--plate-1` (#e6edee), a pale silver chosen so
 * that a frame shot on a light sweep and its mount are one surface with no seam between them.
 * That is the right idea and it was applied to a catalogue that does not have it: of the
 * twenty-eight SKUs with photography, THREE have galleries consistently on the light sweep.
 * Nine are entirely on a dark ground, and sixteen carry both inside the same gallery, so paging
 * through one product's photos flipped the background back and forth. On the product page it
 * showed as a dark studio render floating inside a white rectangle inside a dark page — three
 * grounds, in the wrong order.
 *
 * The ground is read from the frame's own blurhash, which every image record already carries and
 * which encodes exactly this: decode it to an 8×8 and average the four corners. No new data
 * file, no pipeline run, nothing to keep in step — the hash and the picture cannot disagree,
 * because the hash is made of the picture.
 *
 * The corner colour is not used as the mount directly. Half these frames corner on olive or
 * brown, and a mount in that colour is mud rather than a decision. It picks WHICH mount — the
 * silver sweep, or a dark one belonging to the store's own surfaces — and then leans that mount
 * a little toward the frame so the two still meet without an edge.
 *
 * ── Why this does not replace lib/plate-colors.ts ────────────────────────────
 *
 * That table is generated by scripts/blend-skus.mts from the real border pixels of each SKU's
 * FIRST frame, which is more accurate than a lossy hash and is what the product card already
 * paints. Checked against it, this function agrees on 25 of the 26 SKUs it covers — glass being
 * the one it reads darker, which is fair for a translucent product.
 *
 * So: the table is exact and per-SKU, this is approximate and per-frame, and the gallery needs
 * per-frame because sixteen of the twenty-eight galleries carry both light and dark frames. The
 * gallery uses the table for frame one — so arriving from a card is seamless — and this for the
 * rest.
 */

/** Above this, the frame was shot on a sweep and the silver mount is the one it wants. */
const LIGHT_GROUND = 165;

/** How far the mount leans toward the frame's own corner colour. Enough to lose the seam. */
const TINT = '22%';

export interface Ground {
  /** A CSS colour for `--plate` / `--plate-stage`. */
  plate: string;
  /** True when the frame is on the light sweep the default mount was designed for. */
  light: boolean;
}

/**
 * The mount for one frame, or null when there is no hash to read — in which case the stylesheet's
 * own default applies and nothing changes.
 */
export function groundFor(blurhash: string | null | undefined): Ground | null {
  if (!blurhash) return null;
  let px: Uint8ClampedArray;
  try {
    px = decode(blurhash, 8, 8);
  } catch {
    /* A malformed hash is not worth a 500 on a product page. */
    return null;
  }
  const at = (x: number, y: number) => {
    const i = (y * 8 + x) * 4;
    return [px[i], px[i + 1], px[i + 2]] as const;
  };
  const pts = [at(0, 0), at(7, 0), at(0, 7), at(7, 7)];
  const rgb = [0, 1, 2].map((c) => Math.round(pts.reduce((sum, p) => sum + p[c], 0) / pts.length));
  const hex = `#${rgb.map((v) => v.toString(16).padStart(2, '0')).join('')}`;
  /* Plain mean, not relative luminance: this is asking "is the paper light or dark", which is a
     question about the ink on the page rather than about how the eye weights green. */
  const light = (rgb[0] + rgb[1] + rgb[2]) / 3 >= LIGHT_GROUND;
  return { plate: `color-mix(in oklab, ${hex} ${TINT}, var(${light ? '--plate-1' : '--plate-dark'}))`, light };
}
