import 'server-only';
import type { FacetConfig, FilterState, SkuSearchDoc } from '@buildobjects/catalog';
import categoriesJson from '../data/catalogue/categories.json';
import facetsJson from '../data/catalogue/facets.json';
import flagshipJson from '../data/catalogue/flagship.json';
import listingsJson from '../data/catalogue/listings.json';
import searchAllJson from '../data/catalogue/search-all.json';
import skusJson from '../data/catalogue/skus.json';
import type { CategoryCard } from './data';

/**
 * The catalogue, frozen.
 *
 * Thirty-seven categories and twenty-eight SKUs is a megabyte of JSON. Serving that from MySQL
 * plus Meilisearch means a deployment cannot render a single page until two hosts exist, two
 * connection strings are correct and a dump has been restored — which is a lot of infrastructure
 * to stand up in front of a catalogue smaller than one of its own product photographs.
 *
 * So the snapshot ships in the repo and the database becomes an optimisation rather than a
 * dependency. Every loader tries the live path first and falls back here, which means:
 *
 *   · a clone renders the whole store with `pnpm dev` and nothing else running;
 *   · Vercel serves it with no environment variables at all;
 *   · a database outage degrades the store to yesterday's catalogue instead of to an error page.
 *
 * The snapshot is generated by `apps/web/scripts/export-catalogue.mts`, which takes it by calling
 * the real loaders — so these objects are shape-identical to the live ones by construction rather
 * than by a second mapping that could drift.
 */

export const staticCategories = categoriesJson as unknown as CategoryCard[];
export const staticFlagship = flagshipJson as unknown as SkuSearchDoc[];
const skus = skusJson as unknown as Record<string, unknown>;
const listings = listingsJson as unknown as Record<string, StaticSearchResult>;
const facetConfigs = facetsJson as unknown as Record<string, FacetConfig | null>;
const searchAll = searchAllJson as unknown as StaticSearchResult;

export interface StaticSearchResult {
  hits: SkuSearchDoc[];
  total: number;
  page: number;
  totalPages: number;
  facetDistribution: Record<string, Record<string, number>>;
  facetStats: Record<string, { min: number; max: number }>;
  processingTimeMs: number;
  query: string;
}

export function staticSkuPage(code: string): unknown | null {
  return skus[code.toLowerCase()] ?? null;
}

export function staticFacetConfig(category: string | null): FacetConfig | null {
  return category ? (facetConfigs[category] ?? null) : null;
}

/** Every SKU the snapshot knows about, unfiltered. */
function allHits(): SkuSearchDoc[] {
  return searchAll.hits.length ? searchAll.hits : staticFlagship;
}

const HITS_PER_PAGE = 24;

/**
 * Search, filter, sort and facet the frozen catalogue in memory.
 *
 * Twenty-eight documents. A linear scan over them is faster than the network hop it replaces, so
 * there is no index here and no need for one — the moment this stops being true the catalogue has
 * outgrown a snapshot and should be on the live path anyway.
 */
export function staticSearch(state: FilterState & { q: string; page: number; category?: string }, fixedCategory?: string): StaticSearchResult {
  const category = fixedCategory ?? state.category;
  /* The pre-computed listing is exact for the unfiltered view, which is the common case. */
  const untouched = !state.q && !state.brand?.length && !state.price && !state.stock && !Object.keys(state.attrs ?? {}).length;
  if (untouched && state.page === 1) {
    if (category && listings[category]) return listings[category];
    if (!category) return searchAll;
  }

  let hits = allHits();
  if (category) hits = hits.filter((h) => h.category === category);

  if (state.q) {
    const q = state.q.toLowerCase();
    hits = hits.filter((h) =>
      [h.name, h.brand, h.category_name, h.model_no, h.short_description, ...(h.synonyms ?? []), ...(h.spec_text ?? [])]
        .filter(Boolean)
        .some((v) => String(v).toLowerCase().includes(q)),
    );
  }
  if (state.brand?.length) {
    const want = new Set(state.brand);
    hits = hits.filter((h) => want.has(h.brand) || want.has(h.brand_slug));
  }
  if (state.stock) hits = hits.filter((h) => h.in_stock);
  if (state.price) {
    // Either end of the range may be open — the rail lets you set only a floor or only a ceiling.
    const [lo, hi] = state.price;
    const min = lo ?? Number.NEGATIVE_INFINITY;
    const max = hi ?? Number.POSITIVE_INFINITY;
    hits = hits.filter((h) => h.selling_price !== null && h.selling_price >= min && h.selling_price <= max);
  }
  for (const [key, want] of Object.entries(state.attrs ?? {})) {
    hits = hits.filter((h) => {
      const v = (h as unknown as Record<string, unknown>)[key];
      if (want === true) return v !== undefined && v !== null && v !== false;
      const wanted = Array.isArray(want) ? want.map(String) : [String(want)];
      if (Array.isArray(v)) return v.some((x) => wanted.includes(String(x)));
      return wanted.includes(String(v));
    });
  }

  const price = (h: SkuSearchDoc) => h.selling_price ?? Number.POSITIVE_INFINITY;
  if (state.sort === 'price_asc') hits = [...hits].sort((a, b) => price(a) - price(b));
  else if (state.sort === 'price_desc') hits = [...hits].sort((a, b) => price(b) - price(a));

  /* Facets are counted over the result set, which is what makes a struck-through value honest. */
  const facetDistribution: Record<string, Record<string, number>> = {};
  const bump = (facet: string, value: string) => {
    facetDistribution[facet] ??= {};
    facetDistribution[facet][value] = (facetDistribution[facet][value] ?? 0) + 1;
  };
  for (const h of hits) {
    bump('category', h.category);
    bump('brand', h.brand);
    bump('in_stock', String(h.in_stock));
    for (const [k, v] of Object.entries(h as unknown as Record<string, unknown>)) {
      if (v === null || v === undefined || typeof v === 'object') continue;
      if (['id', 'sku_code', 'slug', 'name', 'short_description', 'selling_price', 'mrp'].includes(k)) continue;
      bump(k, String(v));
    }
  }
  const prices = hits.map((h) => h.selling_price).filter((p): p is number => typeof p === 'number');
  const facetStats: Record<string, { min: number; max: number }> = {};
  if (prices.length) facetStats.selling_price = { min: Math.min(...prices), max: Math.max(...prices) };

  const page = Math.max(1, state.page);
  const totalPages = Math.max(1, Math.ceil(hits.length / HITS_PER_PAGE));
  return {
    hits: hits.slice((page - 1) * HITS_PER_PAGE, page * HITS_PER_PAGE),
    total: hits.length,
    page,
    totalPages,
    facetDistribution,
    facetStats,
    processingTimeMs: 0,
    query: state.q,
  };
}
