'use client';

import type { EstimateResult, Tier } from '@buildobjects/estimator';
import React from 'react';
import { IconRoom } from '@/components/icons';
import { useScrollLock } from '@/components/useDismiss';
import { mediaUrl } from '@/lib/media';
import LivingHouse from './LivingHouse';

const HouseTurntable = React.lazy(() => import('./HouseTurntable'));

/**
 * The house, as a photograph of itself.
 *
 * This started as an SVG elevation — rectangles for storeys, a parallelogram for the roof. It was
 * accurate and it looked like a diagram, and a diagram is the wrong answer for the one screen
 * where someone decides whether to spend thirty lakhs. So the house is now a real architectural
 * render, and there are thirty of them: five storey counts × three finish qualities × solar on
 * and off, pre-generated by `services/pipeline/tools/house-renders.mts`.
 *
 * Pre-generated, not live. Generating on demand would put twenty seconds and a network call
 * between a person dragging the floors control and seeing anything, which is the opposite of what
 * this is for. Thirty stills swap instantly.
 *
 * The SVG survives as the fallback. If a render is missing — the matrix has not been run, the
 * media store is empty on a fresh clone — the page still draws the house rather than showing a
 * grey box, and everything below the image keeps working.
 */

const FLOORS_MAX = 4;

/** Mirrors `houseKey` in services/pipeline/tools/house-renders.mts. One naming rule, two places. */
function houseSrc(floors: number, tier: Tier, solar: boolean, size: 'card' | 'hero'): string {
  const f = Math.max(0, Math.min(FLOORS_MAX, floors));
  return `estimator/house/${f}-${tier}${solar ? '-solar' : ''}-${size}.webp`;
}

/**
 * The mesh for this configuration, served by /3d/*.
 *
 * There is no `-solar` variant: solar is a handful of dark rectangles on a roof that image-to-3D
 * will not resolve at any price, so the 3D matrix is floors x finish only and the still render is
 * what carries the panels. See packages/assets3d/tools/house-3d.mts.
 */
function houseModelSrc(floors: number, tier: Tier): string {
  return `/3d/house/${Math.max(0, Math.min(FLOORS_MAX, floors))}-${tier}.glb`;
}

/**
 * What the estimate is paying for that the render deliberately does not show.
 *
 * The renders are of the building alone — no compound wall, no porch, no camera — because each
 * of those is a line item that can be switched off, and a picture showing a wall the estimate did
 * not price is a picture that lies. Naming them under the image is both honest and more useful:
 * it is a checklist of what is included.
 */
function alsoIncluded(result: EstimateResult): string[] {
  const { inputs } = result;
  const items: string[] = [];
  if (inputs.compoundWall) items.push('Compound wall');
  if (inputs.parking) items.push('Car parking');
  if (inputs.addons.cctv) items.push('CCTV');
  if (inputs.addons.fireSafety) items.push('Fire safety');
  return items;
}

export default function HouseRender({ result, highlight = null }: { result: EstimateResult; highlight?: string | null }) {
  const { inputs, derived } = result;
  const solar = inputs.addons.solar;
  const src = houseSrc(inputs.floors, inputs.tier, solar, 'hero');
  const url = mediaUrl(src);

  /*
   * Two stacked images and a crossfade, rather than one <img> whose src changes. Swapping the src
   * of a single element shows the old frame until the new bytes arrive and then cuts — on a slow
   * connection that reads as a stall, and on a fast one as a flicker. Here the incoming render is
   * decoded underneath and only revealed once it is ready, so a change of floors dissolves.
   */
  const [shown, setShown] = React.useState<string | null>(url);
  const [incoming, setIncoming] = React.useState<string | null>(null);
  const [failed, setFailed] = React.useState(false);
  const [turntable, setTurntable] = React.useState(false);
  /* Covers the viewport, so the page behind it must not scroll — see useScrollLock. */
  useScrollLock(turntable);

  /*
   * Whether this configuration has a mesh at all. Asked once per configuration with a HEAD, so
   * the "Turn it around" button only ever appears when pressing it will work — an interactive
   * affordance that opens onto an error is worse than no affordance.
   */
  const modelSrc = houseModelSrc(inputs.floors, inputs.tier);
  const [hasModel, setHasModel] = React.useState(false);
  React.useEffect(() => {
    let alive = true;
    setTurntable(false);
    fetch(modelSrc, { method: 'HEAD' })
      .then((r) => alive && setHasModel(r.ok))
      .catch(() => alive && setHasModel(false));
    return () => {
      alive = false;
    };
  }, [modelSrc]);

  React.useEffect(() => {
    if (!url || url === shown) return;
    let alive = true;
    const img = new Image();
    img.src = url;
    img
      .decode()
      .then(() => {
        if (!alive) return;
        setIncoming(url);
        // one frame for the incoming layer to paint at opacity 0, then fade it up
        requestAnimationFrame(() => {
          if (!alive) return;
          setShown(url);
          setIncoming(null);
        });
      })
      .catch(() => {
        if (alive) setFailed(true);
      });
    return () => {
      alive = false;
    };
  }, [url, shown]);

  const extras = alsoIncluded(result);

  // No render on disk yet: draw it instead of showing a hole.
  if (failed || !url) return <LivingHouse result={result} highlight={highlight} />;

  return (
    <figure className="hr" aria-labelledby="hr-cap">
      <div className="hr-frame">
        {turntable && (
          <React.Suspense fallback={<div className="ht-veil">Loading the 3D model…</div>}>
            <HouseTurntable src={modelSrc} label={`${derived.floorsLabel}, ${TIER_WORD[inputs.tier]} finish`} onClose={() => setTurntable(false)} />
          </React.Suspense>
        )}
        {!turntable && shown && (
          <img
            key={shown}
            className="hr-img"
            src={shown}
            alt={`A ${derived.floorsLabel} house, ${TIER_WORD[inputs.tier]} finish${solar ? ', with rooftop solar' : ''}`}
            onError={() => setFailed(true)}
            decoding="async"
          />
        )}
        {!turntable && incoming && <img className="hr-img hr-img--in" src={incoming} alt="" aria-hidden decoding="async" />}
        {!turntable && hasModel && (
          <button type="button" className="hr-3d" onClick={() => setTurntable(true)}>
            <IconRoom size={15} /> Turn it around
          </button>
        )}
        {/* The one figure that has to survive on top of a photograph. */}
        <figcaption id="hr-cap" className="hr-cap" hidden={turntable}>
          <span className="hr-cap-main">{derived.floorsLabel}</span>
          <span className="hr-cap-dot" aria-hidden>
            ·
          </span>
          <span className="hr-cap-sub">{TIER_WORD[inputs.tier]} finish</span>
          {solar && (
            <>
              <span className="hr-cap-dot" aria-hidden>
                ·
              </span>
              <span className="hr-cap-sub">Rooftop solar</span>
            </>
          )}
        </figcaption>
      </div>
      <div className="hr-foot">
        <span className="hr-foot-k">
          <span className="fig">{Math.round(derived.builtUpSqft).toLocaleString('en-IN')}</span> sq ft built on{' '}
          <span className="fig">{Math.round(derived.plotAreaSqft).toLocaleString('en-IN')}</span> sq ft of land
        </span>
        {extras.length > 0 && <span className="hr-foot-x">Also in this estimate: {extras.join(' · ')}</span>}
      </div>
    </figure>
  );
}

/** The word a person uses, not the key the rate card uses. */
const TIER_WORD: Record<Tier, string> = { basic: 'Standard', medium: 'Better', premium: 'Premium' };
